backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "versionlog"
    label: "Version Log"
    files:
      - name: "versionlog"
        label: "Version Log"
        file: "_data/versionlog.json"
        fields:
          - label: "Entries"
            name: "entries"
            widget: "list"
            fields:
              - label: "Version"
                name: "version"
                widget: "string"
                hint: "e.g. 1.21.11"
              - label: "Date"
                name: "date"
                widget: "string"
                hint: "e.g. 1 May 2025"
              - label: "Notes"
                name: "notes"
                widget: "text"
                hint: "What changed in this version"
